<#
.SYNOPSIS
    IdentityAgent Email Helper for automated Codex Scroll delivery.
    
.DESCRIPTION
    Formats HTML Codex Scrolls into Microsoft Graph API-ready email payloads.
    Supports multiple recipients, customizable templates, and Power BI integration.
    Preserves SHA256 placeholders and lineage anchors for sponsor transparency.
    
.NOTES
    Module: Get-CodexEmailBody.psm1
    Version: 1.0.0
    Author: IntelIntent Team
    Requires: Microsoft Graph API authentication
#>

function Get-CodexEmailBody {
    <#
    .SYNOPSIS
        Wraps HTML Codex Scroll into Graph API email payload.
        
    .DESCRIPTION
        Creates Microsoft Graph API-compliant email JSON for automated sponsor delivery.
        Embeds HTML scroll content with preserved SHA256 signatures and Power BI anchors.
        
    .PARAMETER ScrollPath
        Path to HTML Codex Scroll file generated by New-CodexScroll.
        
    .PARAMETER Recipients
        Array of recipient email addresses. Supports multiple sponsors.
        
    .PARAMETER Subject
        Email subject line. Default includes session ID and timestamp.
        
    .PARAMETER IncludeSummary
        If specified, prepends executive summary with checkpoint metrics.
        
    .PARAMETER PowerBIDashboardUrl
        Optional Power BI dashboard URL for direct lineage exploration.
        
    .PARAMETER Template
        Email template style: Executive, Technical, Compliance, or Standard.
        
    .PARAMETER Attachments
        Array of file paths to attach (e.g., Markdown scroll, PDF reports).
        
    .EXAMPLE
        $payload = Get-CodexEmailBody -ScrollPath ".\Week1_Codex_Scroll.html" -Recipients @("sponsor@example.com")
        Invoke-RestMethod -Uri "https://graph.microsoft.com/v1.0/me/sendMail" -Method POST -Body $payload
        
    .EXAMPLE
        $payload = Get-CodexEmailBody `
            -ScrollPath ".\Week1_Codex_Scroll.html" `
            -Recipients @("sponsor1@example.com", "sponsor2@example.com") `
            -Subject "Phase 4 Week 1 Complete - Codex Lineage Report" `
            -IncludeSummary `
            -PowerBIDashboardUrl "https://app.powerbi.com/groups/.../dashboards/..." `
            -Template "Executive" `
            -Attachments @(".\Week1_Codex_Scroll.md", ".\Week1_Summary.pdf")
        
        Send-CodexEmail -Payload $payload
    #>
    
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateScript({ Test-Path $_ })]
        [string]$ScrollPath,
        
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string[]]$Recipients,
        
        [Parameter(Mandatory = $false)]
        [string]$Subject,
        
        [Parameter(Mandatory = $false)]
        [switch]$IncludeSummary,
        
        [Parameter(Mandatory = $false)]
        [string]$PowerBIDashboardUrl,
        
        [Parameter(Mandatory = $false)]
        [ValidateSet("Executive", "Technical", "Compliance", "Standard")]
        [string]$Template = "Standard",
        
        [Parameter(Mandatory = $false)]
        [string[]]$Attachments = @()
    )
    
    # Read HTML scroll content
    if (-not (Test-Path $ScrollPath)) {
        throw "Codex Scroll not found: $ScrollPath"
    }
    
    $htmlContent = Get-Content -Path $ScrollPath -Raw -ErrorAction Stop
    
    # Extract session metadata from checkpoint file if available
    $checkpointFile = ".\Week1_Checkpoints.json"
    $sessionMetadata = @{
        SessionID = "Unknown"
        CheckpointCount = 0
        SuccessRate = 0
        Timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    }
    
    if (Test-Path $checkpointFile) {
        try {
            $checkpoints = Get-Content $checkpointFile -Raw | ConvertFrom-Json
            $sessionMetadata.SessionID = $checkpoints.SessionID
            $sessionMetadata.CheckpointCount = $checkpoints.Checkpoints.Count
            
            $successCount = ($checkpoints.Checkpoints | Where-Object { $_.Status -eq "Success" }).Count
            if ($checkpoints.Checkpoints.Count -gt 0) {
                $sessionMetadata.SuccessRate = [Math]::Round(($successCount / $checkpoints.Checkpoints.Count) * 100, 1)
            }
        }
        catch {
            Write-Warning "Could not parse checkpoint metadata: $($_.Exception.Message)"
        }
    }
    
    # Default subject if not provided
    if (-not $Subject) {
        $Subject = "IntelIntent Phase 4 Codex Scroll - $($sessionMetadata.Timestamp)"
    }
    
    # Build email body based on template
    $emailBody = switch ($Template) {
        "Executive" {
            Get-ExecutiveEmailTemplate -HtmlContent $htmlContent -Metadata $sessionMetadata -PowerBIDashboardUrl $PowerBIDashboardUrl -IncludeSummary:$IncludeSummary
        }
        "Technical" {
            Get-TechnicalEmailTemplate -HtmlContent $htmlContent -Metadata $sessionMetadata -PowerBIDashboardUrl $PowerBIDashboardUrl -IncludeSummary:$IncludeSummary
        }
        "Compliance" {
            Get-ComplianceEmailTemplate -HtmlContent $htmlContent -Metadata $sessionMetadata -PowerBIDashboardUrl $PowerBIDashboardUrl -IncludeSummary:$IncludeSummary
        }
        default {
            Get-StandardEmailTemplate -HtmlContent $htmlContent -Metadata $sessionMetadata -PowerBIDashboardUrl $PowerBIDashboardUrl -IncludeSummary:$IncludeSummary
        }
    }
    
    # Build recipient array
    $toRecipients = @()
    foreach ($recipient in $Recipients) {
        $toRecipients += @{
            emailAddress = @{
                address = $recipient
            }
        }
    }
    
    # Build attachment array if provided
    $emailAttachments = @()
    foreach ($attachmentPath in $Attachments) {
        if (Test-Path $attachmentPath) {
            $fileName = [System.IO.Path]::GetFileName($attachmentPath)
            $fileBytes = [System.IO.File]::ReadAllBytes($attachmentPath)
            $base64Content = [Convert]::ToBase64String($fileBytes)
            
            $emailAttachments += @{
                "@odata.type" = "#microsoft.graph.fileAttachment"
                name = $fileName
                contentBytes = $base64Content
            }
        }
        else {
            Write-Warning "Attachment not found: $attachmentPath"
        }
    }
    
    # Construct Graph API email payload
    $payload = @{
        message = @{
            subject = $Subject
            body = @{
                contentType = "HTML"
                content = $emailBody
            }
            toRecipients = $toRecipients
            importance = "high"
        }
        saveToSentItems = "true"
    }
    
    # Add attachments if present
    if ($emailAttachments.Count -gt 0) {
        $payload.message.attachments = $emailAttachments
    }
    
    # Return JSON payload
    return ($payload | ConvertTo-Json -Depth 10 -Compress)
}

function Get-ExecutiveEmailTemplate {
    param(
        [string]$HtmlContent,
        [hashtable]$Metadata,
        [string]$PowerBIDashboardUrl,
        [switch]$IncludeSummary
    )
    
    $summarySection = ""
    if ($IncludeSummary) {
        $summarySection = @"
<div style="background: #f8f9fa; padding: 25px; border-radius: 10px; margin-bottom: 30px; border-left: 5px solid #667eea;">
    <h2 style="color: #333; margin-top: 0; font-size: 22px;">📊 Executive Summary</h2>
    <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
        <tr style="background: white;">
            <td style="padding: 15px; border: 1px solid #dee2e6; font-weight: bold;">Session ID</td>
            <td style="padding: 15px; border: 1px solid #dee2e6; font-family: monospace;">$($Metadata.SessionID)</td>
        </tr>
        <tr style="background: #f1f3f5;">
            <td style="padding: 15px; border: 1px solid #dee2e6; font-weight: bold;">Checkpoints Completed</td>
            <td style="padding: 15px; border: 1px solid #dee2e6;">$($Metadata.CheckpointCount)</td>
        </tr>
        <tr style="background: white;">
            <td style="padding: 15px; border: 1px solid #dee2e6; font-weight: bold;">Success Rate</td>
            <td style="padding: 15px; border: 1px solid #dee2e6; color: #28a745; font-weight: bold;">$($Metadata.SuccessRate)%</td>
        </tr>
        <tr style="background: #f1f3f5;">
            <td style="padding: 15px; border: 1px solid #dee2e6; font-weight: bold;">Completion Time</td>
            <td style="padding: 15px; border: 1px solid #dee2e6;">$($Metadata.Timestamp)</td>
        </tr>
    </table>
</div>
"@
    }
    
    $dashboardSection = ""
    if ($PowerBIDashboardUrl) {
        $dashboardSection = @"
<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 10px; margin: 30px 0; text-align: center;">
    <h3 style="color: white; margin: 0 0 15px 0;">📈 Interactive Lineage Dashboard</h3>
    <a href="$PowerBIDashboardUrl" style="display: inline-block; background: white; color: #667eea; padding: 12px 30px; border-radius: 5px; text-decoration: none; font-weight: bold;">Open Power BI Dashboard</a>
</div>
"@
    }
    
    return @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>IntelIntent Phase 4 Codex Scroll</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #ffffff;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px; border-radius: 15px; margin-bottom: 30px; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 32px;">🎉 Phase 4 Execution Complete</h1>
        <p style="color: white; margin: 15px 0 0 0; font-size: 18px; opacity: 0.95;">Production Hardening & Codex Lineage Report</p>
    </div>
    
    $summarySection
    
    <div style="background: #e3f2fd; padding: 20px; border-radius: 10px; border-left: 4px solid #2196f3; margin-bottom: 30px;">
        <p style="margin: 0; color: #1565c0; font-size: 16px;"><strong>🔐 Cryptographic Verification:</strong> All checkpoints signed with SHA256. Verify integrity via Power BI dashboard or attached Markdown scroll.</p>
    </div>
    
    $dashboardSection
    
    <div style="margin-top: 30px;">
        <h2 style="color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px;">📜 Detailed Lineage</h2>
        $HtmlContent
    </div>
    
    <div style="background: #f8f9fa; padding: 20px; border-radius: 10px; margin-top: 40px; border-top: 3px solid #667eea;">
        <p style="margin: 0 0 10px 0; color: #666; font-size: 14px;"><strong>Next Steps:</strong></p>
        <ul style="margin: 0; padding-left: 20px; color: #666; font-size: 14px;">
            <li>Review lineage for task-level visibility</li>
            <li>Validate SHA256 signatures in Power BI</li>
            <li>Trace delegation chains via interactive network graph</li>
            <li>Schedule follow-up briefing for Week 2 scale testing</li>
        </ul>
    </div>
    
    <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #dee2e6;">
        <p style="color: #999; font-size: 12px; margin: 0;">IntelIntent Phase 4 Production Hardening | Automated by IdentityAgent</p>
    </div>
</body>
</html>
"@
}

function Get-TechnicalEmailTemplate {
    param(
        [string]$HtmlContent,
        [hashtable]$Metadata,
        [string]$PowerBIDashboardUrl,
        [switch]$IncludeSummary
    )
    
    $summarySection = ""
    if ($IncludeSummary) {
        $summarySection = @"
<div style="background: #2d3748; color: #e2e8f0; padding: 20px; border-radius: 8px; margin-bottom: 25px; font-family: 'Courier New', monospace;">
    <pre style="margin: 0; overflow-x: auto;">
Session Metadata:
├─ ID:          $($Metadata.SessionID)
├─ Checkpoints: $($Metadata.CheckpointCount)
├─ Success:     $($Metadata.SuccessRate)%
└─ Timestamp:   $($Metadata.Timestamp)
    </pre>
</div>
"@
    }
    
    $dashboardSection = ""
    if ($PowerBIDashboardUrl) {
        $dashboardSection = @"
<div style="background: #1a202c; padding: 15px; border-radius: 8px; margin: 25px 0;">
    <p style="color: #a0aec0; margin: 0 0 10px 0; font-family: 'Courier New', monospace;">$ open-powerbi-dashboard</p>
    <a href="$PowerBIDashboardUrl" style="color: #4299e1; text-decoration: none; font-family: 'Courier New', monospace;">→ $PowerBIDashboardUrl</a>
</div>
"@
    }
    
    return @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>IntelIntent Codex Scroll - Technical</title>
</head>
<body style="font-family: 'Courier New', Courier, monospace; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #1a202c; color: #e2e8f0;">
    <div style="background: #2d3748; padding: 30px; border-radius: 8px; margin-bottom: 25px; border-left: 5px solid #4299e1;">
        <h1 style="color: #4299e1; margin: 0; font-size: 28px;">🔧 Phase 4 Technical Report</h1>
        <p style="color: #a0aec0; margin: 10px 0 0 0; font-size: 16px;">Production Hardening Pipeline Execution</p>
    </div>
    
    $summarySection
    
    <div style="background: #2d3748; padding: 15px; border-radius: 8px; margin-bottom: 25px; border-left: 3px solid #48bb78;">
        <p style="margin: 0; color: #48bb78; font-size: 14px;"><strong>✓ Signature Verification:</strong> SHA256 hashes validated. Checkpoint integrity: PASS</p>
    </div>
    
    $dashboardSection
    
    <div style="margin-top: 25px;">
        <h2 style="color: #4299e1; border-bottom: 2px solid #2d3748; padding-bottom: 10px;">📋 Checkpoint Lineage</h2>
        $HtmlContent
    </div>
    
    <div style="background: #2d3748; padding: 15px; border-radius: 8px; margin-top: 30px;">
        <p style="margin: 0; color: #a0aec0; font-size: 12px;">IntelIntent v4.0 | Automated Scroll Generation | IdentityAgent → Graph API</p>
    </div>
</body>
</html>
"@
}

function Get-ComplianceEmailTemplate {
    param(
        [string]$HtmlContent,
        [hashtable]$Metadata,
        [string]$PowerBIDashboardUrl,
        [switch]$IncludeSummary
    )
    
    $summarySection = ""
    if ($IncludeSummary) {
        $summarySection = @"
<div style="background: #fff9e6; padding: 25px; border-radius: 10px; margin-bottom: 30px; border: 2px solid #ffc107;">
    <h2 style="color: #856404; margin-top: 0;">⚖️ Compliance Summary</h2>
    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="padding: 12px; border: 1px solid #ffc107; font-weight: bold;">Audit Trail ID</td>
            <td style="padding: 12px; border: 1px solid #ffc107; font-family: monospace;">$($Metadata.SessionID)</td>
        </tr>
        <tr>
            <td style="padding: 12px; border: 1px solid #ffc107; font-weight: bold;">Total Checkpoints</td>
            <td style="padding: 12px; border: 1px solid #ffc107;">$($Metadata.CheckpointCount)</td>
        </tr>
        <tr>
            <td style="padding: 12px; border: 1px solid #ffc107; font-weight: bold;">Compliance Rate</td>
            <td style="padding: 12px; border: 1px solid #ffc107; color: #28a745; font-weight: bold;">$($Metadata.SuccessRate)%</td>
        </tr>
        <tr>
            <td style="padding: 12px; border: 1px solid #ffc107; font-weight: bold;">Audit Timestamp</td>
            <td style="padding: 12px; border: 1px solid #ffc107;">$($Metadata.Timestamp)</td>
        </tr>
    </table>
</div>
"@
    }
    
    $dashboardSection = ""
    if ($PowerBIDashboardUrl) {
        $dashboardSection = @"
<div style="background: #fff9e6; padding: 20px; border-radius: 10px; margin: 30px 0; text-align: center; border: 2px solid #ffc107;">
    <h3 style="color: #856404; margin: 0 0 15px 0;">📊 SOC 2 Type II Compliance Dashboard</h3>
    <a href="$PowerBIDashboardUrl" style="display: inline-block; background: #ffc107; color: #856404; padding: 12px 30px; border-radius: 5px; text-decoration: none; font-weight: bold;">View Compliance Dashboard</a>
</div>
"@
    }
    
    return @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>IntelIntent Compliance Report</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #ffffff;">
    <div style="background: #ffc107; padding: 40px; border-radius: 15px; margin-bottom: 30px; text-align: center;">
        <h1 style="color: #856404; margin: 0; font-size: 32px;">⚖️ Compliance Audit Report</h1>
        <p style="color: #856404; margin: 15px 0 0 0; font-size: 18px;">SOC 2 Type II | Phase 4 Production Hardening</p>
    </div>
    
    $summarySection
    
    <div style="background: #fff3cd; padding: 20px; border-radius: 10px; border-left: 4px solid #ffc107; margin-bottom: 30px;">
        <p style="margin: 0; color: #856404; font-size: 16px;"><strong>🔒 Audit Controls:</strong></p>
        <ul style="margin: 10px 0 0 0; padding-left: 20px; color: #856404;">
            <li>Immutable checkpoint trail with SHA256 signatures</li>
            <li>RBAC enforcement validated across 4 personas</li>
            <li>Certificate-based authentication (no client secrets)</li>
            <li>Circuit breaker resilience for external services</li>
            <li>Health monitoring with Application Insights telemetry</li>
        </ul>
    </div>
    
    $dashboardSection
    
    <div style="margin-top: 30px;">
        <h2 style="color: #333; border-bottom: 2px solid #ffc107; padding-bottom: 10px;">📜 Audit Trail Lineage</h2>
        $HtmlContent
    </div>
    
    <div style="background: #fff9e6; padding: 20px; border-radius: 10px; margin-top: 40px; border: 2px solid #ffc107;">
        <p style="margin: 0 0 10px 0; color: #856404; font-weight: bold;">Auditor Actions:</p>
        <ul style="margin: 0; padding-left: 20px; color: #856404; font-size: 14px;">
            <li>Verify SHA256 signatures in Power BI Compliance Dashboard</li>
            <li>Review RBAC access logs for unauthorized attempts</li>
            <li>Validate secret rotation schedule (90-day cadence)</li>
            <li>Confirm audit log append-only constraint integrity</li>
        </ul>
    </div>
    
    <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ffc107;">
        <p style="color: #856404; font-size: 12px; margin: 0;">IntelIntent Phase 4 | SOC 2 Type II Compliant | Automated by IdentityAgent</p>
    </div>
</body>
</html>
"@
}

function Get-StandardEmailTemplate {
    param(
        [string]$HtmlContent,
        [hashtable]$Metadata,
        [string]$PowerBIDashboardUrl,
        [switch]$IncludeSummary
    )
    
    $summarySection = ""
    if ($IncludeSummary) {
        $summarySection = @"
<div style="background: #f8f9fa; padding: 20px; border-radius: 10px; margin-bottom: 30px;">
    <h2 style="color: #333; margin-top: 0;">📊 Summary</h2>
    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #dee2e6;"><strong>Session ID:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #dee2e6;">$($Metadata.SessionID)</td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #dee2e6;"><strong>Checkpoints:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #dee2e6;">$($Metadata.CheckpointCount)</td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #dee2e6;"><strong>Success Rate:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #dee2e6;">$($Metadata.SuccessRate)%</td>
        </tr>
    </table>
</div>
"@
    }
    
    $dashboardSection = ""
    if ($PowerBIDashboardUrl) {
        $dashboardSection = @"
<div style="background: #e3f2fd; padding: 20px; border-radius: 10px; margin: 30px 0; text-align: center;">
    <h3 style="color: #1976d2; margin: 0 0 15px 0;">📈 View Lineage Dashboard</h3>
    <a href="$PowerBIDashboardUrl" style="display: inline-block; background: #2196f3; color: white; padding: 12px 30px; border-radius: 5px; text-decoration: none; font-weight: bold;">Open Dashboard</a>
</div>
"@
    }
    
    return @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>IntelIntent Codex Scroll</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #ffffff;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; margin-bottom: 30px;">
        <h1 style="color: white; margin: 0;">📜 IntelIntent Codex Scroll</h1>
        <p style="color: white; margin: 10px 0 0 0; font-size: 16px;">Phase 4 Execution Report</p>
    </div>
    
    $summarySection
    
    <div style="background: #e3f2fd; padding: 20px; border-radius: 10px; border-left: 4px solid #2196f3; margin-bottom: 30px;">
        <p style="margin: 0; color: #1976d2;"><strong>🔐 Cryptographic Verification:</strong> All checkpoints signed with SHA256. Verify integrity via Power BI dashboard.</p>
    </div>
    
    $dashboardSection
    
    <div style="margin-top: 30px;">
        <h2 style="color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px;">📋 Checkpoint Lineage</h2>
        $HtmlContent
    </div>
    
    <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #dee2e6;">
        <p style="color: #999; font-size: 12px; margin: 0;">IntelIntent Phase 4 | Automated by IdentityAgent</p>
    </div>
</body>
</html>
"@
}

function Send-CodexEmail {
    <#
    .SYNOPSIS
        Sends Codex Scroll email via Microsoft Graph API.
        
    .DESCRIPTION
        Wrapper function for simplified email delivery using Graph API.
        Requires valid Graph API access token with Mail.Send permission.
        
    .PARAMETER Payload
        JSON payload from Get-CodexEmailBody.
        
    .PARAMETER AccessToken
        Microsoft Graph API access token. If not provided, attempts to retrieve from Azure CLI.
        
    .EXAMPLE
        $payload = Get-CodexEmailBody -ScrollPath ".\Week1.html" -Recipients @("sponsor@example.com")
        Send-CodexEmail -Payload $payload
        
    .EXAMPLE
        $token = (az account get-access-token --resource https://graph.microsoft.com --query accessToken -o tsv)
        Send-CodexEmail -Payload $payload -AccessToken $token
    #>
    
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Payload,
        
        [Parameter(Mandatory = $false)]
        [string]$AccessToken
    )
    
    # Get access token if not provided
    if (-not $AccessToken) {
        try {
            $AccessToken = (az account get-access-token --resource https://graph.microsoft.com --query accessToken -o tsv)
            if (-not $AccessToken) {
                throw "Failed to retrieve access token from Azure CLI"
            }
        }
        catch {
            throw "Access token required. Authenticate with 'az login' or provide -AccessToken parameter."
        }
    }
    
    # Send email via Graph API
    try {
        $headers = @{
            "Authorization" = "Bearer $AccessToken"
            "Content-Type" = "application/json"
        }
        
        $response = Invoke-RestMethod `
            -Uri "https://graph.microsoft.com/v1.0/me/sendMail" `
            -Method POST `
            -Headers $headers `
            -Body $Payload `
            -ErrorAction Stop
        
        Write-Host "✅ Codex Scroll email sent successfully" -ForegroundColor Green
        return $response
    }
    catch {
        Write-Error "Failed to send email: $($_.Exception.Message)"
        throw
    }
}

function Test-CodexEmailPayload {
    <#
    .SYNOPSIS
        Validates Codex email payload structure.
        
    .DESCRIPTION
        Checks JSON payload for required Graph API fields and structure.
        Useful for debugging before sending.
        
    .PARAMETER Payload
        JSON payload to validate.
        
    .EXAMPLE
        $payload = Get-CodexEmailBody -ScrollPath ".\Week1.html" -Recipients @("test@example.com")
        Test-CodexEmailPayload -Payload $payload
    #>
    
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Payload
    )
    
    try {
        $json = $Payload | ConvertFrom-Json -ErrorAction Stop
        
        # Check required fields
        $requiredFields = @("message")
        $missingFields = @()
        
        foreach ($field in $requiredFields) {
            if (-not $json.$field) {
                $missingFields += $field
            }
        }
        
        if ($missingFields.Count -gt 0) {
            Write-Error "Missing required fields: $($missingFields -join ', ')"
            return $false
        }
        
        # Check message structure
        if (-not $json.message.subject) {
            Write-Warning "Subject is empty"
        }
        
        if (-not $json.message.body) {
            Write-Error "Email body is missing"
            return $false
        }
        
        if (-not $json.message.toRecipients) {
            Write-Error "No recipients specified"
            return $false
        }
        
        Write-Host "✅ Payload structure is valid" -ForegroundColor Green
        Write-Host "   Subject: $($json.message.subject)" -ForegroundColor Cyan
        Write-Host "   Recipients: $($json.message.toRecipients.Count)" -ForegroundColor Cyan
        Write-Host "   Attachments: $($json.message.attachments.Count)" -ForegroundColor Cyan
        
        return $true
    }
    catch {
        Write-Error "Invalid JSON payload: $($_.Exception.Message)"
        return $false
    }
}

# Export module functions
Export-ModuleMember -Function @(
    'Get-CodexEmailBody',
    'Send-CodexEmail',
    'Test-CodexEmailPayload'
)
